//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BamBaiOnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.CommentDetails = new HashSet<CommentDetail>();
        }
    
        public int Postid { get; set; }
        public string Title { get; set; }
        public System.DateTime datepost { get; set; }
        public string content { get; set; }
        public Nullable<int> view { get; set; }
        public Nullable<int> comment { get; set; }
        public Nullable<int> Typeid { get; set; }
        public string image { get; set; }
        public string writer { get; set; }
    
        public virtual TypeBlog TypeBlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentDetail> CommentDetails { get; set; }
    }
}
