//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BamBaiOnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentDetail
    {
        public int commentid { get; set; }
        public int postid { get; set; }
        public string content { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime datecomment { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
