//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BamBaiOnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int CartID { get; set; }
        public int Quantity { get; set; }
        public int ProductID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CustomerID { get; set; }
        public decimal thanhtien
        {
            get
            {
                return Quantity * Product.UnitCost;
            }
        }
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
